const states = [
  {
    AK: {
      // Which state
      abbr: "AK", // Postal abbreviation
      full: "Alaska", // AP abbreviation
      ap: "Alaska", // Full name
      x: 0, // x coordinate of square
      y: 72, // y coordinate of square
      w: 66, // width
      h: 66, // height
    },
    AL: {
      abbr: "AL",
      full: "Alabama",
      ap: "Ala.",
      x: 504,
      y: 432,
      w: 66,
      h: 66,
    },
    AR: {
      abbr: "AR",
      full: "Arkansas",
      ap: "Ark.",
      x: 360,
      y: 360,
      w: 66,
      h: 66,
    },
    AZ: {
      abbr: "AZ",
      full: "Arizona",
      ap: "Ariz.",
      x: 144,
      y: 360,
      w: 66,
      h: 66,
    },
    CA: {
      abbr: "CA",
      full: "California",
      ap: "Calif.",
      x: 72,
      y: 288,
      w: 66,
      h: 66,
    },
    CO: {
      abbr: "CO",
      full: "Colorado",
      ap: "Colo.",
      x: 216,
      y: 288,
      w: 66,
      h: 66,
    },
    CT: {
      abbr: "CT",
      full: "Connecticut",
      ap: "Conn.",
      x: 720,
      y: 216,
      w: 66,
      h: 66,
    },
    DC: {
      abbr: "DC",
      full: "Washington, D.C.",
      ap: "D.C.",
      x: 648,
      y: 360,
      w: 66,
      h: 66,
    },
    DE: {
      abbr: "DE",
      full: "Delaware",
      ap: "Del.",
      x: 720,
      y: 288,
      w: 66,
      h: 66,
    },
    FL: {
      abbr: "FL",
      full: "Florida",
      ap: "Fla.",
      x: 648,
      y: 504,
      w: 66,
      h: 66,
    },
    GA: {
      abbr: "GA",
      full: "Georgia",
      ap: "Ga.",
      x: 576,
      y: 432,
      w: 66,
      h: 66,
    },
    HI: {
      abbr: "HI",
      full: "Hawaii",
      ap: "Hawaii",
      x: 72,
      y: 504,
      w: 66,
      h: 66,
    },
    IA: {
      abbr: "IA",
      full: "Iowa",
      ap: "Iowa",
      x: 360,
      y: 216,
      w: 66,
      h: 66,
    },
    ID: {
      abbr: "ID",
      full: "Idaho",
      ap: "Idaho",
      x: 144,
      y: 144,
      w: 66,
      h: 66,
    },
    IL: {
      abbr: "IL",
      full: "Illinois",
      ap: "Ill.",
      x: 432,
      y: 144,
      w: 66,
      h: 66,
    },
    IN: {
      abbr: "IN",
      full: "Indiana",
      ap: "Ind.",
      x: 432,
      y: 216,
      w: 66,
      h: 66,
    },
    KS: {
      abbr: "KS",
      full: "Kansas",
      ap: "Kan.",
      x: 288,
      y: 360,
      w: 66,
      h: 66,
    },
    KY: {
      abbr: "KY",
      full: "Kentucky",
      ap: "Ky.",
      x: 432,
      y: 288,
      w: 66,
      h: 66,
    },
    LA: {
      abbr: "LA",
      full: "Louisiana",
      ap: "La.",
      x: 360,
      y: 432,
      w: 66,
      h: 66,
    },
    MA: {
      abbr: "MA",
      full: "Massachusetts",
      ap: "Mass.",
      x: 720,
      y: 144,
      w: 66,
      h: 66,
    },
    MD: {
      abbr: "MD",
      full: "Maryland",
      ap: "Md.",
      x: 648,
      y: 288,
      w: 66,
      h: 66,
    },
    ME: {
      abbr: "ME",
      full: "Maine",
      ap: "Maine",
      x: 792.8,
      y: 0,
      w: 66,
      h: 66,
    },
    MI: {
      abbr: "MI",
      full: "Michigan",
      ap: "Mich",
      x: 504,
      y: 144,
      w: 66,
      h: 66,
    },
    MN: {
      abbr: "MN",
      full: "Minnesota",
      ap: "Minn.",
      x: 360,
      y: 144,
      w: 66,
      h: 66,
    },
    MO: {
      abbr: "MO",
      full: "Missouri",
      ap: "Mo.",
      x: 360,
      y: 288,
      w: 66,
      h: 66,
    },
    MS: {
      abbr: "MS",
      full: "Mississippi",
      ap: "Miss.",
      x: 432,
      y: 432,
      w: 66,
      h: 66,
    },
    MT: {
      abbr: "MT",
      full: "Montana",
      ap: "Mont.",
      x: 216,
      y: 144,
      w: 66,
      h: 66,
    },
    NC: {
      abbr: "NC",
      full: "North Carolina",
      ap: "N.C.",
      x: 504,
      y: 360,
      w: 66,
      h: 66,
    },
    ND: {
      abbr: "ND",
      full: "North Dakota",
      ap: "N.D.",
      x: 288,
      y: 144,
      w: 66,
      h: 66,
    },
    NE: {
      abbr: "NE",
      full: "Nebraska",
      ap: "Neb.",
      x: 288,
      y: 288,
      w: 66,
      h: 66,
    },
    NH: {
      abbr: "NH",
      full: "New Hampshire",
      ap: "N.H.",
      x: 792.8,
      y: 72,
      w: 66,
      h: 66,
    },
    NJ: {
      abbr: "NJ",
      full: "New Jersey",
      ap: "N.J.",
      x: 648,
      y: 216,
      w: 66,
      h: 66,
    },
    NM: {
      abbr: "NM",
      full: "New Mexico",
      ap: "N.M.",
      x: 216,
      y: 360,
      w: 66,
      h: 66,
    },
    NV: {
      abbr: "NV",
      full: "Nevada",
      ap: "Nev.",
      x: 144,
      y: 216,
      w: 66,
      h: 66,
    },
    NY: {
      abbr: "NY",
      full: "New York",
      ap: "N.Y.",
      x: 648,
      y: 144,
      w: 66,
      h: 66,
    },
    OH: {
      abbr: "OH",
      full: "Ohio",
      ap: "Ohio",
      x: 504,
      y: 216,
      w: 66,
      h: 66,
    },
    OK: {
      abbr: "OK",
      full: "Oklahoma",
      ap: "Okla.",
      x: 288,
      y: 432,
      w: 66,
      h: 66,
    },
    OR: {
      abbr: "OR",
      full: "Oregon",
      ap: "Ore.",
      x: 72,
      y: 216,
      w: 66,
      h: 66,
    },
    PA: {
      abbr: "PA",
      full: "Pennsylvania",
      ap: "Pa.",
      x: 576,
      y: 216,
      w: 66,
      h: 66,
    },
    RI: {
      abbr: "RI",
      full: "Rhode Island",
      ap: "R.I.",
      x: 792.8,
      y: 216,
      w: 66,
      h: 66,
    },
    SC: {
      abbr: "SC",
      full: "South Carolina",
      ap: "S.C.",
      x: 576,
      y: 360,
      w: 66,
      h: 66,
    },
    SD: {
      abbr: "SD",
      full: "South Dakota",
      ap: "S.D.",
      x: 288,
      y: 216,
      w: 66,
      h: 66,
    },
    TN: {
      abbr: "TN",
      full: "Tennessee",
      ap: "Tenn.",
      x: 432,
      y: 360,
      w: 66,
      h: 66,
    },
    TX: {
      abbr: "TX",
      full: "Texas",
      ap: "Texas",
      x: 288,
      y: 504,
      w: 66,
      h: 66,
    },
    UT: {
      abbr: "UT",
      full: "Utah",
      ap: "Utah",
      x: 144,
      y: 288,
      w: 66,
      h: 66,
    },
    VA: {
      abbr: "VA",
      full: "Virginia",
      ap: "Va.",
      x: 576,
      y: 288,
      w: 66,
      h: 66,
    },
    VT: {
      abbr: "VT",
      full: "Vermont",
      ap: "Vt.",
      x: 720,
      y: 72,
      w: 66,
      h: 66,
    },
    WA: {
      abbr: "WA",
      full: "Washington",
      ap: "Wash.",
      x: 72,
      y: 144,
      w: 66,
      h: 66,
    },
    WI: {
      abbr: "WI",
      full: "Wisconsin",
      ap: "Wis.",
      x: 432,
      y: 72,
      w: 66,
      h: 66,
    },
    WV: {
      abbr: "WV",
      full: "West Virginia",
      ap: "W. Va.",
      x: 504,
      y: 288,
      w: 66,
      h: 66,
    },
    WY: {
      abbr: "WY",
      full: "Wyoming",
      ap: "Wyo.",
      x: 216,
      y: 216,
      w: 66,
      h: 66,
    },
  },
];

export default states;
